version: "3.7"
services:
    # image project
    laravel_8:
        build:
            args:
                user: dprado
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - laravel-eti

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8180:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-eti

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - laravel-eti

    # queue
    queue:
        build:
            args:
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: queue
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - laravel-eti

networks:
    laravel-eti:
        driver: bridge
